// Generated by CoffeeScript 1.3.3
(function() {
  var Kata,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Kata = (function() {

    function Kata(input) {
      this.input = input;
      this.base = this.input;
      this.memo = [];
    }

    Kata.prototype.split = function() {
      var digits;
      digits = [];
      while (this.base >= 10) {
        digits.push(this.base % 10);
        this.base = ~~(this.base / 10);
      }
      digits.push(this.base);
      digits.reverse();
      console.log(digits);
      return digits;
    };

    Kata.prototype.check = function() {
      var digits, n, sum, _i, _len;
      sum = 0;
      digits = this.split();
      for (_i = 0, _len = digits.length; _i < _len; _i++) {
        n = digits[_i];
        sum += n * n;
      }
      if ((__indexOf.call(this.memo, sum) >= 0)) {
        return "" + this.input + " is not a happy number";
      } else {
        this.base = sum;
        this.memo.push(sum);
        if (this.base === 1) {
          return "" + this.input + " is a happy number";
        }
        return this.check();
      }
    };

    return Kata;

  })();

  window.Kata = Kata;

}).call(this);
